/*
 * Munux Rust Static Library - C Interface
 *
 * Generated by cbindgen. Do not edit by hand.
 * Regenerate with: make rust-headers
 */

#ifndef MUNUX_RS_H
#define MUNUX_RS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Allocate `size` bytes from the kernel heap.
 *
 * Returns a null pointer on failure (out of memory, zero size,
 * or heap not initialized).
 */
uint8_t *munux_rs_alloc(size_t size);

/**
 * Free a pointer previously returned by `munux_rs_alloc`.
 *
 * Safety: `ptr` must either be null or have been returned by
 * `munux_rs_alloc` and not yet freed.
 */
void munux_rs_free(uint8_t *ptr);

/**
 * Initialize the Rust-backed kernel heap.
 *
 * Must be called exactly once, after the initial heap region has been
 * mapped writable by the C-side `heap_init`.
 *
 * Safety: `start` must point to a contiguous, page-aligned, mapped
 * writable region of length at least `initial_size`. `max` is the
 * upper bound the C side is willing to grow the heap to via
 * `munux_c_heap_grow`.
 */
void munux_rs_heap_init(size_t start, size_t initial_size, size_t max);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* MUNUX_RS_H */
