/*
 * Munux Rust Static Library - C Interface
 *
 * Generated by cbindgen. Do not edit by hand.
 * Regenerate with: make rust-headers
 */

#ifndef MUNUX_RS_H
#define MUNUX_RS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Allocate `size` bytes from the kernel heap.
 *
 * Returns a null pointer on failure (out of memory, zero size,
 * or heap not initialized).
 */
uint8_t *munux_rs_alloc(size_t size);

/**
 * Free a pointer previously returned by `munux_rs_alloc`.
 *
 * Safety: `ptr` must either be null or have been returned by
 * `munux_rs_alloc` and not yet freed.
 */
void munux_rs_free(uint8_t *ptr);

/**
 * Initialize the Rust-backed kernel heap.
 *
 * Must be called exactly once, after the initial heap region has been
 * mapped writable by the C-side `heap_init`.
 *
 * Safety: `start` must point to a contiguous, page-aligned, mapped
 * writable region of length at least `initial_size`. `max` is the
 * upper bound the C side is willing to grow the heap to via
 * `munux_c_heap_grow`.
 */
void munux_rs_heap_init(size_t start, size_t initial_size, size_t max);

/**
 * Allocate `size` bytes from the kernel heap, aligned to `align`
 * (a power of two). Returns null on failure. Must be freed with
 * `munux_rs_free_aligned`, never with `munux_rs_free`.
 */
uint8_t *munux_rs_alloc_aligned(size_t size, size_t align);

/**
 * Free a pointer previously returned by `munux_rs_alloc_aligned`.
 *
 * Safety: `ptr` must either be null or have been returned by
 * `munux_rs_alloc_aligned` and not yet freed.
 */
void munux_rs_free_aligned(uint8_t *ptr);

/**
 * Run the in-kernel VFS/tmpfs self-test. Returns 0 on success, non-zero
 * on failure. Requires the heap to be initialized.
 */
int32_t munux_rs_vfs_selftest(void);

/**
 * Run the ext2 read-only self-test against the Primary Master disk.
 * Returns 0 on success, non-zero on failure. Requires a valid ext2 image.
 */
int32_t munux_rs_ext2_selftest(void);

/**
 * Run the buffer-cache self-test (hit/miss). Requires an attached disk.
 * Returns 0 on success, non-zero on failure.
 */
int32_t munux_rs_bcache_selftest(void);

/** Initialize the VFS (mount tmpfs + default files + fd table). */
void munux_rs_vfs_init(void);

/**
 * Open `path` (`len` bytes). Returns a file descriptor (>= 3) or -1.
 * Safety: `path` must point to `len` readable bytes.
 */
int32_t munux_rs_vfs_open(const uint8_t *path, size_t len);

/**
 * Read up to `len` bytes from `fd` into `buf`. Returns bytes read, 0 at EOF,
 * or -1 on error. Safety: `buf` must point to `len` writable bytes.
 */
int32_t munux_rs_vfs_read(int32_t fd, uint8_t *buf, size_t len);

/** Close `fd`. Returns 0 on success, -1 if the descriptor does not exist. */
int32_t munux_rs_vfs_close(int32_t fd);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* MUNUX_RS_H */
